//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carrent
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab2
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dateofrented { get; set; }
        public Nullable<int> typeofcar { get; set; }
    
        public virtual tab1 tab1 { get; set; }
    }
}
